#!/usr/bin/env bash
# Runs the circuit's `print_parity_vectors` test and freezes the emitted field
# values (Noir prints them as 0x hex) into the JS parity fixture as 32-byte
# FieldHex. This is the single source of truth the Vitest parity test asserts
# against — never hand-edit the JSON; re-run this only when the circuit changes.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/../packages/zk-shared/test/fixtures/parity-vectors.json"
mkdir -p "$(dirname "$OUT")"
export PATH="$HOME/.nargo/bin:$HOME/.bb:$PATH"

RAW="$(cd "$HERE/zelyo_credential" && nargo test print_parity_vectors --show-output 2>&1)"

RAW="$RAW" python3 - "$OUT" <<'PY'
import os, re, json, sys
raw = os.environ["RAW"]
out = sys.argv[1]

def norm(h: str) -> str:
    return "0x" + h.lower().removeprefix("0x").rjust(64, "0")

def get(key: str) -> str:
    m = re.search(rf'(?:^|\s){re.escape(key)}=(0x[0-9a-fA-F]+)', raw)
    if not m:
        raise SystemExit(f"export-vectors: missing key '{key}' in VEC output")
    return norm(m.group(1))

data = {
    "_note": "Generated by circuits/export-vectors.sh from print_parity_vectors. Do not hand-edit.",
    "vectors": [
        {
            "s": get("s"),
            "scope": get("scope"),
            "attributes": {
                "track": get("track"),
                "grade": get("grade"),
                "issueDate": get("issue_date"),
            },
            "idCommitment": get("idCommitment"),
            "attrHash": get("attrHash"),
            "leaf": get("leaf"),
            "nullifier": get("nullifier"),
        }
    ],
}
with open(out, "w") as f:
    f.write(json.dumps(data, indent=2) + "\n")
PY

echo "Wrote $OUT"
